### PR TITLE
Feature/cool look

### PR DESCRIPTION
**Pull request by ajgassner**
Better look and feel

### CODE REVIEW

**Comment by blecher-at** [comment]
I like the visual style very much, but the lineheight is way too much on both my fullhd and 3k monitors.

**Comment by ajgassner** [comment]
please pull and see if it's ok now

**Comment by blecher-at** [comment]
I think 20px is a nice compromise. We can make it configurable later...
I also fixed the avatar size, it scales now with the commit height.

**Comment by blecher-at** [comment]
Looks cleaner when fadeIn("fast") is used. Avatar blinks - but not sure if I like it or not :)

**Comment by blecher-at** [comment]
merged it :)

**Pull request merged**
